author = "Anton Kolomeytsev"
title = "Kekmech Blog"
# The URL the site will be built for
base_url = "https://tonykolomeytsev.github.io"
generate_feed = true
minify_html = true
theme = "papermod"
compile_sass = true
build_search_index = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"

[extra]
# Put all your custom variables here

[extra.papermod]
title = "Kekmech"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["android", "development", "tech", "robotics"]
date_format = "%Y-%m-%d"
show_reading_time = true
show_word_count = true
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
default_toc_open = false
edit_post_url = "https://github.com/tonykolomeytsev/tonykolomeytsev.github.io/tree/master"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
]

home_title = "Kekmech"
home_content = "An underground blog about the technologies I work with, as well as the gauge metrics of my insanity."
social_icons = [
    { url = "https://github.com/tonykolomeytsev", title = "GitHub", icon = "github" },
    { url = "https://t.me/kekmech", title = "Telegram", icon = "telegram" },
    { url = "https://vk.com/kekmech", title = "VK", icon = "vk" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
