on:
  push:
    tags:
      - "v*" # Run when tag matches v*, i.e. v1.0, v20.15.10

name: Generator release

env:
  RELEASE_BIN: tonykolomeytsev-github-io
  GITHUB_REF: "${{ github.ref }}"

jobs:
  build:
    name: Build Rust binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      - name: Install Rust
        run: |
          rustup update --no-self-update
      
      - name: Build
        run: |
          cargo build --release

      - name: Create zip
        run: |
          mkdir ./dist
          mkdir ./artifacts
          mv ./target/release/${{ env.RELEASE_BIN }} ./dist/${{ env.RELEASE_BIN }}
          7z a -tzip ./artifacts/${{ env.RELEASE_BIN }}.zip ./dist
          ls -lah
          pwd

      - name: Upload zip
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: ./artifacts

  release:
    name: GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}

      - name: Download zip
        uses: actions/download-artifact@v1
        with:
          name: artifacts
      
      - name: Release zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/${{ env.RELEASE_BIN }}.zip
          asset_name: ./artifacts/${{ env.RELEASE_BIN }}.zip
          asset_content_type: application/zip
    
    gen:
      name: Generate all pages
      needs: release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Install latest generator binary
          run: |
            export PKG_NAME="default.artifacts.tonykolomeytsev-github-io.zip"
            curl -LJO "https://github.com/tonykolomeytsev/tonykolomeytsev.github.io/releases/latest/download/$PKG_NAME"
            tar -xzf "$PKG_NAME"
            mv ./dist/tonykolomeytsev-github-io /usr/local/bin/tkgio
            tkgio